default['jboss7']['jboss_path'] = '/opt'
default['jboss7']['jboss_home'] = "#{node['jboss7']['jboss_path']}/jboss"
default['jboss7']['jboss_check'] = "#{node['jboss7']['jboss_home']}/bin"
default['jboss7']['jboss_deployments'] = "#{node['jboss7']['jboss_home']}/standalone/deployments"
default['jboss7']['jboss_user'] = 'jboss'
default['jboss7']['jboss_group'] = 'jboss'
default['jboss7']['jboss_version'] = '7.1.1.Final'
default['jboss7']['dl_url'] = "http://download.jboss.org/jbossas/7.1/jboss-as-#{node['jboss7']['jboss_version']}/jboss-as-#{node['jboss7']['jboss_version']}.tar.gz"
default['jboss7']['jboss_tar'] = "/tmp/jboss-as-#{node['jboss7']['jboss_version']}.tar.gz"
default['jboss7']['jvm_min_mem'] = '512m'
default['jboss7']['jvm_max_mem'] = '1024m'
default['jboss7']['jvm_perm_mem'] = '256m'
default['jboss7']['jvm_extra_ops'] = nil
default['jboss7']['ajp_port'] = 8009
default['jboss7']['http_port'] = 8080
default['jboss7']['https_port'] = 8443
default['jboss7']['public_bind_addr'] = '0.0.0.0'
default['jboss7']['mgmt_bind_addr'] = '0.0.0.0'
default['jboss7']['unsecure_bind_addr'] = '0.0.0.0'
# default['jboss7']['admin_user'] = 'admin'
# default['jboss7']['admin_pass'] = 'admin'
default['jboss7']['test_app_url'] = "http://www.cumulogic.com/download/Apps/testweb.zip"
default['jboss7']['test_app_archive'] = "/tmp/testweb.zip"
default['jboss7']['test_app_check'] = "#{node['jboss7']['jboss_deploy']}/testweb"